# The URL the site will be built for
base_url = "https://tarun.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "lightspeed"
title= "Tarun Pothulapati"
description= "Writes about Infra, Networking and Remote Life."

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

footer_links = [
    {url = "$BASE_URL/talks", name = "Talks"},
    {url = "$BASE_URL/projects", name = "Projects"},
    {url = "$BASE_URL/about", name = "About"},
]
